In [2]:
import pandas as pd

In [3]:
data = {
    "Name": ["Aarav", "Diya", "Kabir", "Meera", "Ishaan"],
    "Math": [88, 92, 76, 85, 90],
    "Science": [91, 89, 84, 88, 95],
    "English": [78, 85, 80, 90, 88]
}

df = pd.DataFrame(data)
df

     Name  Math  Science  English
0   Aarav    88       91       78
1    Diya    92       89       85
2   Kabir    76       84       80
3   Meera    85       88       90
4  Ishaan    90       95       88

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Math     5 non-null      int64
 2   Science  5 non-null      int64
 3   English  5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

           Math    Science    English
count   5.00000   5.000000   5.000000
mean   86.20000  89.400000  84.200000
std     6.26099   4.037326   5.118594
min    76.00000  84.000000  78.000000
25%    85.00000  88.000000  80.000000
50%    88.00000  89.000000  85.000000
75%    90.00000  91.000000  88.000000
max    92.00000  95.000000  90.000000