In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('USA_Housing.csv')
df

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386
...,...,...,...,...,...,...,...
4995,60567.944140,7.830362,6.137356,3.46,22837.361035,1.060194e+06,USNS Williams\nFPO AP 30153-7653
4996,78491.275435,6.999135,6.576763,4.02,25616.115489,1.482618e+06,"PSC 9258, Box 8489\nAPO AA 42991-3352"
4997,63390.686886,7.250591,4.805081,2.13,33266.145490,1.030730e+06,"4215 Tracy Garden Suite 076\nJoshualand, VA 01..."
4998,68001.331235,5.534388,7.130144,5.44,42625.620156,1.198657e+06,USS Wallace\nFPO AE 73316
4999,65510.581804,5.992305,6.792336,4.07,46501.283803,1.298950e+06,"37778 George Ridges Apt. 509\nEast Holly, NV 2..."

In [3]:
df.shape

(5000, 7)

In [4]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object
dtypes: float64(6), object(1)
memory usage: 273.6+ KB

In [5]:
df.describe

<bound method NDFrame.describe of       Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0         79545.458574             5.682861                   7.009188
1         79248.642455             6.002900                   6.730821
2         61287.067179             5.865890                   8.512727
3         63345.240046             7.188236                   5.586729
4         59982.197226             5.040555                   7.839388
...                ...                  ...                        ...
4995      60567.944140             7.830362                   6.137356
4996      78491.275435             6.999135                   6.576763
4997      63390.686886             7.250591                   4.805081
4998      68001.331235             5.534388                   7.130144
4999      65510.581804             5.992305                   6.792336

      Avg. Area Number of Bedrooms  Area Population         Price  \
0                             4.09     23086.800503  1.059034e+06
1                             3.09     40173.072174  1.505891e+06
2                             5.13     36882.159400  1.058988e+06
3                             3.26     34310.242831  1.260617e+06
4                             4.23     26354.109472  6.309435e+05
...                            ...              ...           ...
4995                          3.46     22837.361035  1.060194e+06
4996                          4.02     25616.115489  1.482618e+06
4997                          2.13     33266.145490  1.030730e+06
4998                          5.44     42625.620156  1.198657e+06
4999                          4.07     46501.283803  1.298950e+06

                                                Address
0     208 Michael Ferry Apt. 674\nLaurabury, NE 3701...
1     188 Johnson Views Suite 079\nLake Kathleen, CA...
2     9127 Elizabeth Stravenue\nDanieltown, WI 06482...
3                             USS Barnett\nFPO AP 44820
4                            USNS Raymond\nFPO AE 09386
...                                                 ...
4995                   USNS Williams\nFPO AP 30153-7653
4996              PSC 9258, Box 8489\nAPO AA 42991-3352
4997  4215 Tracy Garden Suite 076\nJoshualand, VA 01...
4998                          USS Wallace\nFPO AE 73316
4999  37778 George Ridges Apt. 509\nEast Holly, NV 2...

[5000 rows x 7 columns]>

In [6]:
pd.set_option('display.max_columns',6)

In [7]:
df.head(10)

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,...,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,...,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,...,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,...,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,...,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,...,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386
5,80175.754159,4.988408,6.104512,...,26748.428425,1.068138e+06,"06039 Jennifer Islands Apt. 443\nTracyport, KS..."
6,64698.463428,6.025336,8.147760,...,60828.249085,1.502056e+06,"4759 Daniel Shoals Suite 442\nNguyenburgh, CO ..."
7,78394.339278,6.989780,6.620478,...,36516.358972,1.573937e+06,"972 Joyce Viaduct\nLake William, TN 17778-6483"
8,59927.660813,5.362126,6.393121,...,29387.396003,7.988695e+05,USS Gilbert\nFPO AA 20957
9,81885.927184,4.423672,8.167688,...,40149.965749,1.545155e+06,Unit 9446 Box 0958\nDPO AE 97025

In [8]:
df.tail(15)

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,...,Area Population,Price,Address
4985,75117.042949,6.036275,6.538111,...,43976.031060,1.378938e+06,"PSC 7442, Box 6234\nAPO AP 13017"
4986,71060.406015,5.718839,7.222730,...,34814.585591,1.260241e+06,"5611 Matthew Avenue\nLake Kevin, FM 72963-8891"
4987,65729.222330,6.237787,6.860475,...,25573.854289,1.197073e+06,"641 Lisa Parkways Suite 552\nWest Amandaside, ..."
4988,67637.840665,7.056673,5.774409,...,43846.531340,1.275143e+06,"6066 Sanders Court Apt. 914\nSouth Alexis, FM ..."
4989,47965.406896,5.694638,7.363327,...,46071.947337,8.852050e+05,"19960 Scott Street\nPort Brenda, MO 02292-8651"
4990,52723.876555,5.452237,8.124571,...,14802.088438,4.795006e+05,"86727 Kelly Plaza\nLake Veronica, IL 04474"
4991,74102.191890,5.657841,7.683993,...,24041.270592,1.263721e+06,"2871 John Lodge\nAmychester, GU 61734-5597"
4992,87499.125743,6.403473,4.836091,...,40815.199679,1.568701e+06,Unit 2096 Box 9559\nDPO AE 80983-8797
4993,69639.140896,5.007510,7.778375,...,54056.128430,1.381831e+06,"5259 David Causeway Apt. 975\nSouth Alexstad, ..."
4994,73060.846226,5.293682,6.312253,...,22695.695480,9.053549e+05,"5224 Lamb Passage\nNancystad, GA 16579"
4995,60567.944140,7.830362,6.137356,...,22837.361035,1.060194e+06,USNS Williams\nFPO AP 30153-7653
4996,78491.275435,6.999135,6.576763,...,25616.115489,1.482618e+06,"PSC 9258, Box 8489\nAPO AA 42991-3352"
4997,63390.686886,7.250591,4.805081,...,33266.145490,1.030730e+06,"4215 Tracy Garden Suite 076\nJoshualand, VA 01..."
4998,68001.331235,5.534388,7.130144,...,42625.620156,1.198657e+06,USS Wallace\nFPO AE 73316
4999,65510.581804,5.992305,6.792336,...,46501.283803,1.298950e+06,"37778 George Ridges Apt. 509\nEast Holly, NV 2..."

In [9]:
person = {
    "first": "Corey",
    "last": "Schafer",
    "email": "CoreyMSchafer@gmail.com"
}
people = {
    "first": ["Corey"],
    "last": ["Schafer"],
    "email": ["CoreyMSchafer@gmail.com"]
}
people = {
    "first": ["Corey", "Jane", "John"],
    "last": ["Schafer", "Doe", "Doe"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@email.com", "JohnDoe@email.com"]
}
people['email']

['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']

In [10]:
#we can just convert dictionaries into dataframe suing pandas
df=pd.DataFrame(people)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [11]:
#=============================DATA STRUCTURES IN PYTHON

In [12]:
#SERIES
#Series is a one-dimensional labeled array capable of holding any 
#data type (integers, strings, floating point numbers, Python objects, etc.)
# data can be many different things:a Python dict,an ndarray,a scalar value

s1=pd.Series(np.random.randint(5,10,7))
s=pd.Series(np.random.randn(5))
s

0   -0.424139
1    0.340065
2   -0.295557
3    0.271203
4    1.256486
dtype: float64

In [13]:
#NaN stands for not a number
#here if we add a foreign value in dictionary the index of that value would be NaN
pd.Series(d, index=["b", "c", "d", "a"])

NameError: name 'd' is not defined

In [ ]:
#if data is a scalar value, the value will be repeated to match the length of index
pd.Series(5.0, index=["a", "b", "c", "d", "e"])

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

In [ ]:
#data can also be fetched from dictionaries
d={"b":0,"a":2,"c":3}
e=pd.Series(d)
print(e)
print(e.loc['b'])
print(e.loc['a'])
print(e.loc['c'])
print(e.loc[:'a'])
#very very important slicing concepts

b    0
a    2
c    3
dtype: int64
0
2
3
b    0
a    2
dtype: int64

In [ ]:
#Series can be converted into array
e.to_numpy()

array([0, 2, 3])

In [ ]:
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s2 = pd.Series([1, 2], index=['b', 'd'])
s1 + s2
#it shoes nan in order to avoid loss of information

a     NaN
b    21.0
c     NaN
d     NaN
dtype: float64

In [ ]:
#============================DATAFRAMES
arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=["A", "B"])
df

   A  B
0  1  2
1  3  4

In [ ]:
s1 = pd.Series([1, 2, 3], index=["a", "b", "c"])
s2 = pd.Series([10, 20], index=["b", "c"])

df = pd.DataFrame({"col1": s1, "col2": s2})
df

   col1  col2
a     1   NaN
b     2  10.0
c     3  20.0

In [ ]:
#When a particular set of columns is passed along with a dict of data, 
# the passed columns override the keys in the dict.
data = {
    "A": [1, 2],
    "B": [3, 4]
}
df = pd.DataFrame(data)
print(df)
df = pd.DataFrame(
    data,
    columns=["B", "A"]
)
df

   A  B
0  1  3
1  2  4

   B  A
0  3  1
1  4  2

In [ ]:
# Column selection, addition, deletion
df=pd.DataFrame({"one":[1,2,3,np.nan]})
print(df)

df["two"]=[1,2,3,4]
print(df)
df["three"] = df["one"] * df["two"]
print(df)
#DELETING AND POPPING COLUMNS
del df["two"]
three = df.pop("three")
df

   one
0  1.0
1  2.0
2  3.0
3  NaN
   one  two
0  1.0    1
1  2.0    2
2  3.0    3
3  NaN    4
   one  two  three
0  1.0    1    1.0
1  2.0    2    4.0
2  3.0    3    9.0
3  NaN    4    NaN

   one
0  1.0
1  2.0
2  3.0
3  NaN

In [ ]:
# TO CREATE A NEW COLUMN IN A DATAFRAME WE USE ASSIGN COLUMN
iris=pd.read_csv("USA_Housing.csv")
iris.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,...,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,...,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,...,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,...,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,...,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,...,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386

In [ ]:
# assign() always returns a copy of the data, leaving the original DataFrame untouched.
iris.assign(ratio=iris["Avg. Area House Age"]/iris["Avg. Area Income"]).head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,...,Price,Address,ratio
0,79545.458574,5.682861,7.009188,...,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701...",0.000071
1,79248.642455,6.002900,6.730821,...,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA...",0.000076
2,61287.067179,5.865890,8.512727,...,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482...",0.000096
3,63345.240046,7.188236,5.586729,...,1.260617e+06,USS Barnett\nFPO AP 44820,0.000113
4,59982.197226,5.040555,7.839388,...,6.309435e+05,USNS Raymond\nFPO AE 09386,0.000084